### ISSUE TITLE
Changing Sample Rate

### ISSUE THREAD

**Issue by pmurley** [krig/go-sox#15]
Hey there. Thanks for working on this - great tool. I'm wondering if there's an easy way to downconvert sample rate of a file. In command line sox, I would just do:

`sox in.wav -r 16000 out.wav`

I can set the rate on the input and the output, but it seems to just slow the audio down, rather than cutting/interpolating samples.

Thanks!

**Comment by krig** [comment]
Hi, and thank you! The effect used to change the sample rate is the `rate` effect, so what you'd want to do is to add that effect to the chain. There are other sample rate changing effects, but AFAIK the `rate` effect is what is used by the `-r` command line argument.

**Comment by pmurley** [comment]
Perfect, that's exactly what I need. Thanks!
