### ISSUE TITLE
example5 error！！

### ISSUE THREAD

**Issue by lihb** [krig/go-sox#21]
hint:
> 2021/06/22 10:54:18 Failed to open memory buffer
      formats: can't open output file `': Invalid argument

anybody konw how to fixed it??

**Comment by krig** [comment]
The example takes a file name as command line argument, it looks like that's the problem!

**Comment by lihb** [comment]
> The example takes a file name as command line argument, it looks like that's the problem!

in windows os failed, but in linux successed,
