### ISSUE TITLE
In-Memory operations issue 

### ISSUE THREAD

**Issue by sean118** [krig/go-sox#9]
Hi. I'm trying to concatenate two .wav files and keep the result in memory only. I'm using Memstream and writing to it using OpenMemstreamWrite. The concatenation process follows example4 of this repo. 

When I write the result to a file for testing, it has the correct, increased file size, but the play duration remains at the length of the first file written into the stream.

The same issue arises with any EffectsChain, that would usually change the duration of the audio.

The reason seems to be the .wav header, that needs to be rewritten after finalising the concatenation or effects chain flow.

Running "sox --ignore-length file.wav file_fixed.wav", fixes the file.

Any idea how to work around this and get the header rewritten inside the Memstream without writing any files to disk?

Thanks

**Comment by sean118** [comment]
Okay, I just solved this issue by creating a new signal with NewSignalInfo() and setting the Length to 0 as in the following:

```
signal := sox.NewSignalInfo(in.Signal().Rate(), in.Signal().Channels(), in.Signal().Precision(), uint64(0), nil)
output = sox.OpenMemstreamWrite(out_stream, signal, in.Encoding(), "wav")`
```

The confusing bit was that writing to file using the following
```
output = sox.OpenWrite("file.wav", in.Signal(), in.Encoding(), "wav")
```
did not require the Signal Length to be re-set.

**Comment by krig** [comment]
Great!

**Comment by sean118** [comment]
Quick Update.

Setting the Length in the header to 0 works fine for me to store and play back the file, but its no good if further processing, eg. use in OpenMemRead(), is required.

I have not found a way to process the wav files and obtain a valid blob with correctly set headers in-memory, so I now temporarily store the resulting file to disk and use it from there.

Any guidance on how to achieve this without writing to disk is much appreciated.

**Comment by krig** [comment]
To be honest, I think you'll have better luck checking with the upstream sox community. I created this go wrapper for sox because I was considering using it for a project, but I know almost nothing about how to actually use it well ;)
